### ISSUE TITLE
提交登录出错

### ISSUE THREAD

**Issue by jinxiw** [xiaohuilam/laravel-admin-nocaptcha#9]
![image](https://user-images.githubusercontent.com/24790399/56989152-642ddc80-6bc4-11e9-8e65-0e7d4318bef4.png)
，大佬能帮助看下吗

**Comment by xiaohuilam** [comment]
## 可能 1
可能 recaptcha 验证不通过的错, 分数低于 0.3 你可以把分值调低一点

```env
RECAPTCHAV3_LOGIN_SCORE=0.3 #改成比 0.3 小的值
```

参考源码:

[src/Providers/RecaptchaV3ServiceProvider.php#L37-L42](https://github.com/xiaohuilam/laravel-recaptchav3/blob/e4224c94bf3da879fb920d51a648ff1010874c07/src/Providers/RecaptchaV3ServiceProvider.php#L37-L42)

```php
$this->app['validator']->extend('recaptchav3', function ($attribute, $value, $paramaters) {
    $action = $paramaters[0];
    $minScore = isset($paramaters[1]) ? (float)$paramaters[1] : 0.5;
    $score = RecaptchaV3Facade::verify($value, $action);
    return $score && $score >= $minScore;
});
```

## 可能 2
~~你的服务器连不上 `www.google.com`, 这种情况你需要配置~~ 后注：应该不会是这个情况。连接不上会报 GuzzleHttp 的异常。
```env
RECAPTCHAV3_ORIGIN=https://www.recaptcha.net
```

**Comment by jinxiw** [comment]
谢谢，第一次用laravel，还不太熟悉。看了下 Lunaweb\RecaptchaV3\RecaptchaV3::verify()返回的信息提示“invalid-input-secret”，我重新检查了下配置项，发现RECAPTCHAV3_SECRET配置名称输错了，现在更改就可以了

**Comment by xiaohuilam** [comment]
@jinxiw 
> 谢谢，第一次用laravel，还不太熟悉。看了下 Lunaweb\RecaptchaV3\RecaptchaV3::verify()返回的信息提示“invalid-input-secret”，我重新检查了下配置项，发现RECAPTCHAV3_SECRET配置名称输错了，现在更改就可以了

OK
